name: reco-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.*
  # PyTorch (CPU build) + marker package cpuonly to ensure CPU-only install from pytorch channel
  - pytorch
  - cpuonly
  # FAISS binary from conda-forge
  - faiss-cpu
  # binary tokenizers + sentencepiece from conda-forge to avoid building from source
  - tokenizers
  - sentencepiece
  # (optional) rust removed because conda provides tokenizers; keep it out to avoid cargo issues
  # - rust

  # Pip-installed Python packages (still inside the conda env)
  - pip:
    - fastapi==0.95.2
    - "uvicorn[standard]==0.22.0"
    - sentence-transformers==2.2.2
    - transformers==4.29.2
    - huggingface-hub==0.25.2
    - pydantic==1.10.7
    - python-multipart==0.0.6
    - aiofiles==0.8.0
    - gunicorn==20.1.0
    - rank_bm25==0.2.2
    - nltk==3.9.1
    - tqdm==4.67.1
    - requests==2.31.0


